## ONLY used for testing
#
#FROM adoptopenjdk/openjdk11:alpine
#
#COPY target/pg5100_8008-exec.jar .
#
#
#CMD java -jar pg5100_8008-exec.jar \
#    --spring.datasource.username="postgres"  \
#    --spring.datasource.password  \
#    --spring.datasource.url="jdbc:postgresql://postgresql-host:5432/postgres"
#




