create sequence hibernate_sequence start with 1 increment by 1;

create table user (
    username varchar(255) not null,
    firstname varchar(255),
    lastname varchar(255),
    email varchar(255),
    enabled boolean not null,
    password varchar(255) not null,
    primary key (username)
);

/*create table trip(
    id bigint generated by default as identity,
    title varchar(255) not null,
    description varchar(255) not null,
    cost INTEGER NOT NULL check (cost>=49 AND cost<=59000),
    location varchar(255) not null,
    date_of_departure date not null,
    primary key(id)
);

create table trip_users(
    users_username varchar(255) not null,
    trip_id bigint not null
);
create table user_trips(
   user_username varchar(255) not null,
   trips_id bigint not null
);

create table purchase
(
    id          bigint generated by default as identity,
    trip_id     bigint not null,
    date_booked date   not null,
    user_username     varchar(255) not null,
    primary key (id)
);*/

/*alter table purchase add constraint FKlq0qkm58rh351bb84y4o5c447 foreign key (user_username) references user;
alter table purchase add constraint FKe537pv7sahdo44b6y2lajtge1 foreign key (trip_id) references trip;
alter table trip_users add constraint FKqchb6i03kpgj2gnq4xhmkydxc foreign key (users_username) references user;
alter table trip_users add constraint FKcrnfc5k5lxdfurq3b97o52dnv foreign key (trip_id) references trip;
alter table user_trips add constraint UK_812qgr2woxiu6e0776qiioy12 foreign key (user_username) references user;
alter table user_trips add constraint FK6qbykpe0c8j68iwgm77hjtvhp foreign key (trips_id) references trip;
*/
