create sequence hibernate_sequence start with 1 increment by 1;

create table user (
    username varchar(255) not null,
    firstname varchar(255),
    lastname varchar(255),
    email varchar(255) not null,
    enabled boolean not null,
    password varchar(255) not null,
    primary key (username)
);

create table movie (
    id bigint generated by default as identity,
    title varchar(255) not null,
    director varchar(255) not null,
    date_of_release date not null,
    primary key(id)
);

create table review
(
    id bigint generated by default as identity,
    movie_id bigint not null,
    review varchar(255) not null,
    date_written date not null,
    user_username varchar(255) not null,
    stars integer not null check (stars<= 5 AND stars>=1),
    primary key (id)
);



